### ISSUE TITLE
Static Collection failing on Django 4.0

### ISSUE THREAD

**Issue by Genetical** [froala/django-froala-editor#112]
Collecting static files seems to be failing on Django 4.0 with the following error message:

```python
Post-processing 'froala_editor/js/languages/nb.js' failed!

Traceback (most recent call last):
  File "/home/runner/work/alpha/alpha/manage.py", line 20, in <module>
    main()
  File "/home/runner/work/alpha/alpha/manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/home/runner/.cache/pypoetry/virtualenvs/alpha-t0XnxaYO-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/alpha-t0XnxaYO-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/runner/.cache/pypoetry/virtualenvs/alpha-t0XnxaYO-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/runner/.cache/pypoetry/virtualenvs/alpha-t0XnxaYO-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/runner/.cache/pypoetry/virtualenvs/alpha-t0XnxaYO-py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/home/runner/.cache/pypoetry/virtualenvs/alpha-t0XnxaYO-py3.9/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'froala_editor/js/languages/nb.js.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f08b7b9d250>.

The JS file 'froala_editor/js/languages/nb.js' references a file which could not be found:
  froala_editor/js/languages/nb.js.map

Please check the URL references in this JS file, particularly any
relative paths which might be pointing to the wrong location.
```

## Environment
This is the environment the step was run in:
```
python = "3.9"
Django = "4.0.3"
whitenoise = "6.0.0"
django-froala-editor = "4.0.9"
```

This process does still work when using Django 3.2.12 so I'm assuming this is a compatibility issue with Django 4.0

**Comment by abdussalam02** [comment]
I am also going through the same issue. If you have found a permanent solution let me know.

**Comment by areski** [comment]
Same issues too :( Any pointer?

**Comment by bastien-aressas** [comment]
Same here ! 😭

**Comment by thomphil** [comment]
It's due to the change in ManifestStaticFilesStorage - it appears to be taking the `.map` comment as a non-comment.

https://docs.djangoproject.com/en/5.1/releases/4.0/
